A=int(input("entrez un entier A="))
print("Vous avez saisi une valeur",A,"de type",type(A))
B=float(input("entrez un réel B="))
print("Vous avez saisi une valeur",B,"de type",type(B))
print(A,"+",B,"=",A+B)
print(A,"*",B,"=",A*B)
print(A,"-",B,"=",A-B)
C=input("entrz une chaine de caractere: ")
print("Vous avez saisi:",C,"de type",type(C))